from routes.auth import auth_bp
from routes.attendance import attendance_bp
from routes.leave import leave_bp
from routes.ml_routes import ml_bp
from routes.placement import placement_bp
from routes.dashboard import dashboard_bp
from routes.project import project_bp
from routes.alert import alert_bp
from routes.admin import admin_bp
from routes.drives import drives_bp
from routes.notifications import notify_bp
from routes.hod import hod_bp
